[tool.poetry]
name = "hexlet_code"
version = "0.1.0"
description = ""
authors = ["angekok"]
packages = [
  { include = "brain_games" },
]

[tool.poetry.dependencies]
python = "3.8.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
