name: GitHub Actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linter
        run: poetry run flake8 brain_games
